import React, { useState, useEffect } from 'react';
import { Brain, Sparkles, Loader, AlertCircle } from 'lucide-react';

export const InterpretationCard = ({ dreamText, interpretation, onCheckAccess }) => {
  const [loading, setLoading] = useState(false);
  const [aiInterpretation, setAiInterpretation] = useState(interpretation || '');
  const [error, setError] = useState('');

  const generateInterpretation = async () => {
    if (!onCheckAccess('interpretation')) return;
    
    setLoading(true);
    setError('');
    
    try {
      // In a real app, this would call OpenAI API
      // For demo purposes, we'll simulate the API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Simulated AI interpretation
      const demoInterpretation = `This dream reflects your subconscious mind processing themes of freedom and exploration. The imagery suggests a desire to break free from current limitations and explore new possibilities in your life. 

Key symbols:
• Flying: Represents liberation and transcendence of obstacles
• Ocean: Symbolizes the vast unconscious mind and emotional depths
• Weightlessness: Indicates a release from burdens or constraints

This type of dream often occurs during periods of personal growth or when facing important life transitions. Your subconscious may be encouraging you to embrace change and trust in your ability to navigate new experiences.`;
      
      setAiInterpretation(demoInterpretation);
    } catch (err) {
      setError('Failed to generate interpretation. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!interpretation && dreamText) {
      generateInterpretation();
    }
  }, [dreamText, interpretation]);

  if (loading) {
    return (
      <div className="bg-gradient-to-r from-primary/5 to-accent/5 rounded-lg p-6">
        <div className="flex items-center justify-center space-x-3">
          <Loader className="h-6 w-6 text-primary animate-spin" />
          <p className="text-body text-text-primary">AI is analyzing your dream...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6">
        <div className="flex items-center space-x-3">
          <AlertCircle className="h-6 w-6 text-red-500" />
          <div>
            <p className="text-body text-red-700">{error}</p>
            <button
              onClick={generateInterpretation}
              className="text-red-600 text-sm underline mt-1"
            >
              Try again
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!aiInterpretation) return null;

  return (
    <div className="bg-gradient-to-r from-primary/5 to-accent/5 rounded-lg p-6">
      <div className="flex items-center space-x-3 mb-4">
        <div className="bg-primary p-2 rounded-lg">
          <Brain className="h-5 w-5 text-white" />
        </div>
        <div>
          <h3 className="text-heading text-text-primary">AI Interpretation</h3>
          <p className="text-caption text-text-secondary">Generated by advanced dream analysis</p>
        </div>
      </div>
      
      <div className="prose prose-sm max-w-none">
        <div className="text-body text-text-primary whitespace-pre-line">
          {aiInterpretation}
        </div>
      </div>
      
      <div className="flex items-center mt-4 pt-4 border-t border-primary/20">
        <Sparkles className="h-4 w-4 text-primary mr-2" />
        <p className="text-caption text-text-secondary">
          This interpretation is generated by AI and should be considered as guidance for self-reflection.
        </p>
      </div>
    </div>
  );
};